/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/-/google-credentials/api/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Encryption Configured */
              encryption_configured: boolean;
              /** Oauth Configured */
              oauth_configured: boolean;
              /** Internal Db Persistent */
              internal_db_persistent: boolean;
              /** Redirect Uri */
              redirect_uri: string;
              /** Can Connect */
              can_connect: boolean;
              /** Can Add Service Account */
              can_add_service_account: boolean;
              /** Is Admin */
              is_admin: boolean;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/-/google-credentials/api/credentials": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Credentials */
              credentials: components["schemas"]["ListedCredential"][];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/-/google-credentials/api/admin/credentials": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Credentials */
              credentials: components["schemas"]["AdminCredentialInfo"][];
              /** Actor Names */
              actor_names: {
                [key: string]: string;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/-/google-credentials/api/service-accounts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * Label
             * @default
             */
            label?: string;
            /**
             * Key Json
             * Format: password
             */
            key_json: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Id */
              id: string;
              /** Type */
              type: string;
              /** Label */
              label: string;
              /** Google Email */
              google_email: string | null;
              /** Scopes */
              scopes: string[];
              /** Status */
              status: string;
              /** Status Detail */
              status_detail: string | null;
              /** Is Owner */
              is_owner: boolean;
              /** Share With Email */
              share_with_email: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/-/google-credentials/api/credentials/{credential_id}/rename": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          credential_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Label */
            label: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Id */
              id: string;
              /** Type */
              type: string;
              /** Label */
              label: string;
              /** Google Email */
              google_email: string | null;
              /** Scopes */
              scopes: string[];
              /** Status */
              status: string;
              /** Status Detail */
              status_detail: string | null;
              /** Is Owner */
              is_owner: boolean;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/-/google-credentials/api/credentials/{credential_id}/rotate-key": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          credential_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /**
             * Key Json
             * Format: password
             */
            key_json: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Id */
              id: string;
              /** Type */
              type: string;
              /** Label */
              label: string;
              /** Google Email */
              google_email: string | null;
              /** Scopes */
              scopes: string[];
              /** Status */
              status: string;
              /** Status Detail */
              status_detail: string | null;
              /** Is Owner */
              is_owner: boolean;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/-/google-credentials/api/credentials/{credential_id}/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          credential_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Id */
              id: string;
              /** Type */
              type: string;
              /**
               * Revoked
               * @default null
               */
              revoked: boolean | null;
              /**
               * Revoke Error
               * @default null
               */
              revoke_error: string | null;
              /**
               * Client Email
               * @default null
               */
              client_email: string | null;
              /**
               * Private Key Id
               * @default null
               */
              private_key_id: string | null;
              /**
               * Project Id
               * @default null
               */
              project_id: string | null;
              /**
               * Cloud Console Url
               * @default null
               */
              cloud_console_url: string | null;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/-/google-credentials": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/-/google-credentials/admin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/-/google-credentials/connect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/-/google-credentials/oauth/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ListedCredential
     * @description ``CredentialInfo`` plus what the management page (ticket 14) needs to
     *     decide which controls to show. Returned by ``GET /api/credentials``; the
     *     extra fields are additive, so each item still reads as a
     *     ``CredentialInfo``. Never a secret, nor who else used or can use it.
     */
    ListedCredential: {
      /** Id */
      id: string;
      /** Type */
      type: string;
      /** Label */
      label: string;
      /** Google Email */
      google_email: string | null;
      /** Scopes */
      scopes: string[];
      /** Status */
      status: string;
      /** Status Detail */
      status_detail: string | null;
      /** Is Owner */
      is_owner: boolean;
      /** Role */
      role: ("User" | "Editor" | "Manager") | null;
      /** Can Edit */
      can_edit: boolean;
      /** Can Manage */
      can_manage: boolean;
      /** Last Used At */
      last_used_at: string | null;
      /** Missing Scopes */
      missing_scopes: string[];
    };
    /**
     * AdminCredentialInfo
     * @description One credential as a ``google-credentials-admin`` sees it in the "All
     *     credentials" view (ticket 15): ``CredentialInfo`` plus who owns it and
     *     who used it last. Information only: it never grants use (D6).
     */
    AdminCredentialInfo: {
      /** Id */
      id: string;
      /** Type */
      type: string;
      /** Label */
      label: string;
      /** Google Email */
      google_email: string | null;
      /** Scopes */
      scopes: string[];
      /** Status */
      status: string;
      /** Status Detail */
      status_detail: string | null;
      /** Is Owner */
      is_owner: boolean;
      /** Owner Id */
      owner_id: string;
      /** Created By */
      created_by: string;
      /** Last Used At */
      last_used_at: string | null;
      /** Last Used By */
      last_used_by: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
