/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EncryptionConfigured = boolean;
export type OauthConfigured = boolean;
export type InternalDbPersistent = boolean;
export type RedirectUri = string;
export type CanConnect = boolean;
export type CanAddServiceAccount = boolean;
export type IsAdmin = boolean;
export type Id = string;
export type Type = string;
export type Label = string;
export type GoogleEmail = string | null;
export type Scopes = string[];
export type Status = string;
export type StatusDetail = string | null;
export type IsOwner = boolean;
export type OwnerId = string;
export type CreatedBy = string;
export type LastUsedAt = string | null;
export type LastUsedBy = string | null;
export type Credentials = AdminCredentialInfo[];
export type ManageUrl = string;

/**
 * The ``/-/google-auth/admin`` "All credentials" page (ticket 15).
 * Information only: nothing here lets the admin use a credential (D6).
 */
export interface AdminPageData {
  status: StatusResponse;
  credentials: Credentials;
  actor_names: ActorNames;
  manage_url: ManageUrl;
  [k: string]: unknown;
}
/**
 * What the management page needs for its setup notices (ticket 14).
 */
export interface StatusResponse {
  encryption_configured: EncryptionConfigured;
  oauth_configured: OauthConfigured;
  internal_db_persistent: InternalDbPersistent;
  redirect_uri: RedirectUri;
  can_connect: CanConnect;
  can_add_service_account: CanAddServiceAccount;
  is_admin: IsAdmin;
  [k: string]: unknown;
}
/**
 * One credential as a ``google-auth-admin`` sees it in the "All
 * credentials" view (ticket 15): ``CredentialInfo`` plus who owns it and
 * who used it last. Information only: it never grants use (D6).
 */
export interface AdminCredentialInfo {
  id: Id;
  type: Type;
  label: Label;
  google_email: GoogleEmail;
  scopes: Scopes;
  status: Status;
  status_detail: StatusDetail;
  is_owner: IsOwner;
  owner_id: OwnerId;
  created_by: CreatedBy;
  last_used_at: LastUsedAt;
  last_used_by: LastUsedBy;
  [k: string]: unknown;
}
export interface ActorNames {
  [k: string]: string;
}
