/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EncryptionConfigured = boolean;
export type OauthConfigured = boolean;
export type InternalDbPersistent = boolean;
export type RedirectUri = string;
export type CanConnect = boolean;
export type CanAddServiceAccount = boolean;
export type IsAdmin = boolean;

/**
 * The ``/-/google-auth`` page (placeholder until ticket 14).
 */
export interface IndexPageData {
  status: StatusResponse;
  [k: string]: unknown;
}
/**
 * What the management page needs for its setup notices (ticket 14).
 */
export interface StatusResponse {
  encryption_configured: EncryptionConfigured;
  oauth_configured: OauthConfigured;
  internal_db_persistent: InternalDbPersistent;
  redirect_uri: RedirectUri;
  can_connect: CanConnect;
  can_add_service_account: CanAddServiceAccount;
  is_admin: IsAdmin;
  [k: string]: unknown;
}
